name: Bump version.txt
on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Check versions
      run: |
        echo Reserved for REPO_NAME=${GITHUB_REPOSITORY##*/}
        echo GITHUB_REF=${GITHUB_REF}
        echo EXTRACT_GITHUB_REF=${GITHUB_REF##*/}
        echo EXTRACT_GITHUB_REF_HEADS=$(echo ${GITHUB_REF#refs/heads/})
        echo $(ls)

        cd $REPO_NAME
        git checkout ${GITHUB_REF##*/}
        git checkout $(echo ${GITHUB_REF#refs/heads/})
    - name: Bump version
      run: |
        echo "${GITHUB_REF##*/}"

        git pull ${GITHUB_REF##*/}
        git fetch -t
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        t=$(git describe --tags `git rev-list --tags --max-count=1`)
        new_version=$(python .github/return_new_version.py $t)
        echo $new_version > version.txt
        git add version.txt
        git commit -m "Version ${new_version}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
