name: Bump version.txt
on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Bump version
      run: |
        echo $CURRENT_BRANCH
        git pull $CURRENT_BRANCH
        git fetch -t
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        t=$(git describe --tags `git rev-list --tags --max-count=1`)
        new_version=$(python .github/return_new_version.py $t)
        echo $new_version > version.txt
        git add version.txt
        git commit -m "Version ${new_version}"
      env:
        CURRENT_BRANCH: ${{ github.head_ref }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
